name: CI - Development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21 (using Zulufx)
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Run Integration Tests
        run: mvn verify -P integration-tests

      - name: Run UAT (Karate DSL)
        run: mvn test -P uat