name: CI/CD Pipeline for Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21 (using Zulufx)
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Run Regression Tests (JUnit 5, TestContainers)
        run: mvn test -P regression-tests

  build-and-deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and Push Docker Image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/my-repository/private-chat:latest .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/my-repository/private-chat:latest